openapi: 3.0.0
info:
  title: ParDespue API
  description: API para gestionar usuarios, roles, cápsulas, contenidos, notificaciones y más.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Servidor local

paths:
  /users:
    get:
      summary: Obtener todos los usuarios
      tags:
        - Users
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Error interno del servidor
    post:
      summary: Crear un nuevo usuario
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Error de validación
        '500':
          description: Error interno del servidor

  /users/{id}:
    get:
      summary: Obtener un usuario por ID
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID del usuario
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
    put:
      summary: Actualizar un usuario
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: Usuario actualizado exitosamente
        '400':
          description: Error de validación
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
    delete:
      summary: Eliminar un usuario
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID del usuario
      responses:
        '200':
          description: Usuario eliminado exitosamente
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor

  /roles:
    get:
      summary: Obtener todos los roles
      tags:
        - Roles
      responses:
        '200':
          description: Lista de roles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
        '500':
          description: Error interno del servidor

  /capsules:
    get:
      summary: Obtener todas las cápsulas
      tags:
        - Capsules
      responses:
        '200':
          description: Lista de cápsulas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Capsule'
        '500':
          description: Error interno del servidor
    post:
      summary: Crear una nueva cápsula
      tags:
        - Capsules
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CapsuleInput'
      responses:
        '201':
          description: Cápsula creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Capsule'
        '400':
          description: Error de validación
        '500':
          description: Error interno del servidor

  /contents:
    get:
      summary: Obtener todos los contenidos
      tags:
        - Contents
      responses:
        '200':
          description: Lista de contenidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'
        '500':
          description: Error interno del servidor

  /notifications:
    get:
      summary: Obtener todas las notificaciones
      tags:
        - Notifications
      responses:
        '200':
          description: Lista de notificaciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
        '500':
          description: Error interno del servidor

  /categories:
    get:
      summary: Obtener todas las categorías
      tags:
        - Categories
      responses:
        '200':
          description: Lista de categorías
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '500':
          description: Error interno del servidor

  /subscriptions:
    get:
      summary: Obtener todas las suscripciones
      tags:
        - Subscriptions
      responses:
        '200':
          description: Lista de suscripciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '500':
          description: Error interno del servidor

  /transactions:
    get:
      summary: Obtener todas las transacciones
      tags:
        - Transactions
      responses:
        '200':
          description: Lista de transacciones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '500':
          description: Error interno del servidor

  /recipients/{userId}/{capsuleId}/{roleId}:
    get:
      summary: Obtener un destinatario por clave compuesta
      tags:
        - Recipients
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
          description: ID del usuario
        - name: capsuleId
          in: path
          required: true
          schema:
            type: integer
          description: ID de la cápsula
        - name: roleId
          in: path
          required: true
          schema:
            type: integer
          description: ID del rol
      responses:
        '200':
          description: Destinatario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipient'
        '404':
          description: Destinatario no encontrado
        '500':
          description: Error interno del servidor

  /comments:
    get:
      summary: Obtener todos los comentarios
      tags:
        - Comments
      responses:
        '200':
          description: Lista de comentarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        '500':
          description: Error interno del servidor

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
    UserInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    Role:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Capsule:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        creationDate:
          type: string
          format: date-time
        openingDate:
          type: string
          format: date-time
        privacy:
          type: string
    CapsuleInput:
      type: object
      properties:
        title:
          type: string
        creationDate:
          type: string
          format: date-time
        openingDate:
          type: string
          format: date-time
        privacy:
          type: string
    Content:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        filePath:
          type: string
    Notification:
      type: object
      properties:
        id:
          type: integer
        message:
          type: string
        sentDate:
          type: string
          format: date-time
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
    Subscription:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
    Transaction:
      type: object
      properties:
        id:
          type: integer
        amount:
          type: number
          format: float
        paymentMethod:
          type: string
    Recipient:
      type: object
      properties:
        userId:
          type: integer
        capsuleId:
          type: integer
        roleId:
          type: integer
    Comment:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        creationDate:
          type: string
          format: date-time